### ISSUE TITLE
Grid View

### ISSUE THREAD

**Issue by Maweill** [chainhackers/superhack-2023#7]
- [x] Import Phaser
- [x] Implement visual representation of a cell with the ability to click on it
- [x] Create a field with dimensions of 100x100 cells

**Comment by utgarda** [comment]
Keep in mind it should eventually become scrollable to show a part of the infinite grid. Doesn't have to be exactly 100x100, see what fits your screen ratio best.

**Comment by utgarda** [comment]
Keep in mind it should eventually become scrollable to show a part of the infinite grid. Doesn't have to be exactly 100x100, see what fits your screen ratio best.
