### ISSUE TITLE
Vite Project and Redux Container

### ISSUE THREAD

**Issue by Maweill** [chainhackers/superhack-2023#8]
- Create a Vite project
- - Install yarn, react, redux, rainbow, wagmi
- - Configure build and run settings
- Implement redux state `RootState: game, wallet, api`
- - `GameState: currentGameInfo?, currentTransaction?`
- - - `GameInfo: gameId, moveId, moveResult?`
- - - `Transaction: hash, progress`
- - `WalletState: client?, signer?, chainFormattedName?, isConnected`
- - `ApiState: status`
- - - `ApiStatus: IDLE, STARTED, PENDING, WAITING_RESPONSE, SUCCESS, ERROR`

**Comment by utgarda** [comment]
Very detailed, really cool! We can drop `network` from tx state for the hackathon version - single chain deploy should be enough, or indeed leave it there if it feels more comfortable.
